"""Localized section headers for resume templates."""

SECTION_HEADERS: dict[str, dict[str, str]] = {
    "en": {
        "professional_summary": "Professional Summary",
        "experience": "Experience",
        "education": "Education",
        "skills": "Skills",
        "certifications": "Certifications",
        "projects": "Projects",
        "linkedin": "LinkedIn",
        "github": "GitHub",
        "portfolio": "Portfolio",
        "gpa": "GPA",
        "technologies": "Technologies",
    },
    "es": {
        "professional_summary": "Resumen Profesional",
        "experience": "Experiencia",
        "education": "Educación",
        "skills": "Habilidades",
        "certifications": "Certificaciones",
        "projects": "Proyectos",
        "linkedin": "LinkedIn",
        "github": "GitHub",
        "portfolio": "Portafolio",
        "gpa": "Promedio",
        "technologies": "Tecnologías",
    },
    "fr": {
        "professional_summary": "Résumé Professionnel",
        "experience": "Expérience",
        "education": "Formation",
        "skills": "Compétences",
        "certifications": "Certifications",
        "projects": "Projets",
        "linkedin": "LinkedIn",
        "github": "GitHub",
        "portfolio": "Portfolio",
        "gpa": "Moyenne",
        "technologies": "Technologies",
    },
    "de": {
        "professional_summary": "Berufsprofil",
        "experience": "Berufserfahrung",
        "education": "Ausbildung",
        "skills": "Fähigkeiten",
        "certifications": "Zertifizierungen",
        "projects": "Projekte",
        "linkedin": "LinkedIn",
        "github": "GitHub",
        "portfolio": "Portfolio",
        "gpa": "Notendurchschnitt",
        "technologies": "Technologien",
    },
    "pt": {
        "professional_summary": "Resumo Profissional",
        "experience": "Experiência",
        "education": "Formação",
        "skills": "Competências",
        "certifications": "Certificações",
        "projects": "Projetos",
        "linkedin": "LinkedIn",
        "github": "GitHub",
        "portfolio": "Portfólio",
        "gpa": "Média",
        "technologies": "Tecnologias",
    },
    "it": {
        "professional_summary": "Profilo Professionale",
        "experience": "Esperienza",
        "education": "Formazione",
        "skills": "Competenze",
        "certifications": "Certificazioni",
        "projects": "Progetti",
        "linkedin": "LinkedIn",
        "github": "GitHub",
        "portfolio": "Portfolio",
        "gpa": "Media",
        "technologies": "Tecnologie",
    },
    "zh": {
        "professional_summary": "专业概述",
        "experience": "工作经历",
        "education": "教育背景",
        "skills": "专业技能",
        "certifications": "证书资质",
        "projects": "项目经验",
        "linkedin": "领英",
        "github": "GitHub",
        "portfolio": "作品集",
        "gpa": "绩点",
        "technologies": "技术栈",
    },
    "ja": {
        "professional_summary": "職務要約",
        "experience": "職歴",
        "education": "学歴",
        "skills": "スキル",
        "certifications": "資格",
        "projects": "プロジェクト",
        "linkedin": "LinkedIn",
        "github": "GitHub",
        "portfolio": "ポートフォリオ",
        "gpa": "GPA",
        "technologies": "技術",
    },
    "ko": {
        "professional_summary": "전문 요약",
        "experience": "경력",
        "education": "학력",
        "skills": "기술",
        "certifications": "자격증",
        "projects": "프로젝트",
        "linkedin": "LinkedIn",
        "github": "GitHub",
        "portfolio": "포트폴리오",
        "gpa": "학점",
        "technologies": "기술 스택",
    },
    "ar": {
        "professional_summary": "الملخص المهني",
        "experience": "الخبرة",
        "education": "التعليم",
        "skills": "المهارات",
        "certifications": "الشهادات",
        "projects": "المشاريع",
        "linkedin": "LinkedIn",
        "github": "GitHub",
        "portfolio": "معرض الأعمال",
        "gpa": "المعدل",
        "technologies": "التقنيات",
    },
    "nl": {
        "professional_summary": "Professioneel Profiel",
        "experience": "Werkervaring",
        "education": "Opleiding",
        "skills": "Vaardigheden",
        "certifications": "Certificeringen",
        "projects": "Projecten",
        "linkedin": "LinkedIn",
        "github": "GitHub",
        "portfolio": "Portfolio",
        "gpa": "Gemiddelde",
        "technologies": "Technologieën",
    },
    "ru": {
        "professional_summary": "Профессиональное резюме",
        "experience": "Опыт работы",
        "education": "Образование",
        "skills": "Навыки",
        "certifications": "Сертификаты",
        "projects": "Проекты",
        "linkedin": "LinkedIn",
        "github": "GitHub",
        "portfolio": "Портфолио",
        "gpa": "Средний балл",
        "technologies": "Технологии",
    },
    "pl": {
        "professional_summary": "Profil Zawodowy",
        "experience": "Doświadczenie",
        "education": "Wykształcenie",
        "skills": "Umiejętności",
        "certifications": "Certyfikaty",
        "projects": "Projekty",
        "linkedin": "LinkedIn",
        "github": "GitHub",
        "portfolio": "Portfolio",
        "gpa": "Średnia",
        "technologies": "Technologie",
    },
}


def get_section_headers(language: str = "en") -> dict[str, str]:
    """Get section headers for a given language code, falling back to English."""
    return SECTION_HEADERS.get(language, SECTION_HEADERS["en"])
